// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /cancelProductOrder/{order.Id}_post for http method type POST in rest-assured framework

RoostTestHash=77166fb926


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;

public class CancelProductOrderOrderIdPostTest {

	private static final String TEST_DATA_PATH = "src/test/java/com/bootexample4/RoostTest/cancelProductOrder_order.IdPostTest.csv";

	private static final List<Integer> VALID_STATUS_CODES = Arrays.asList(200, 400, 401, 403, 404, 406, 423, 429, 500,
			503, 504);

	private List<Map<String, String>> envList;

	@BeforeEach
	public void setUp() {
		TestDataLoader dataLoader = new TestDataLoader();
		String[] envVarsList = { "order.Id" };
		envList = dataLoader.load(TEST_DATA_PATH, envVarsList);
	}

	@Test
	public void cancelProductOrderOrderIdPostTest() {
		this.setUp();
		int testNumber = 1;

		for (Map<String, String> testData : envList) {
			// Base URI setup: Default to local server if "nnnn_BASE_URL" is absent
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://127.0.0.1:4026");

			JSONObject requestBody = new JSONObject(testData.getOrDefault("RequestBody", "{}"));

			// Send POST request
			Response response = given().pathParam("order.Id", testData.getOrDefault("order.Id", ""))
				.contentType(ContentType.JSON)
				.body(requestBody.toString())
				.when()
				.post("/cancelProductOrder/{order.Id}")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case %d: cancelProductOrderOrderIdPost_Test\n", testNumber++);
			System.out.println("Request: POST /cancelProductOrder/{order.Id}");
			System.out.println("Status Code: " + response.statusCode());

			// Validate status code
			validateStatusCode(response, testData);

			// Process response content type
			JsonPath jsonResponse = parseResponse(response);

			// Handle specific HTTP status codes
			handleResponseByStatusCode(response, jsonResponse);
		}
	}

	private void validateStatusCode(Response response, Map<String, String> testData) {
		int statusCode = response.statusCode();

		if (testData.containsKey("statusCode")) {
			String expectedStatusCode = testData.get("statusCode");

			if (expectedStatusCode.contains("X")) {
				MatcherAssert.assertThat(
						"Expected status code category " + expectedStatusCode + ", but received " + statusCode,
						Integer.toString(statusCode).charAt(0), equalTo(expectedStatusCode.charAt(0)));
			}
			else {
				MatcherAssert.assertThat("Status code mismatch", String.valueOf(statusCode),
						equalTo(expectedStatusCode));
			}
		}
		else {
			MatcherAssert.assertThat("Unknown status code received", statusCode, is(in(VALID_STATUS_CODES)));
		}
	}

	private JsonPath parseResponse(Response response) {
		String contentType = response.getContentType();

		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = response.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
			return new JsonPath(jsonResponse.toString());
		}

		if (contentType.contains("application/json")) {
			return response.jsonPath();
		}

		throw new IllegalArgumentException("Unsupported content type: " + contentType);
	}

	private void handleResponseByStatusCode(Response response, JsonPath jsonResponse) {
		int statusCode = response.statusCode();

		switch (statusCode) {
			case 200:
				validateSuccessResponse(jsonResponse);
				break;
			case 400:
				validateErrorResponse(jsonResponse, "Description: Bad Request");
				break;
			case 404:
				validateNotFoundResponse(jsonResponse, "Description: Not Found");
				break;
			case 422:
				validateUnprocessableEntityResponse(jsonResponse, "Description: Unprocessable Entity");
				break;
			default:
				System.out.println("Unhandled status code: " + statusCode);
		}
	}

	private void validateSuccessResponse(JsonPath response) {
		System.out.println("Description: Success");
		validateCommonResponseStructure(response);
	}

	private void validateErrorResponse(JsonPath response, String description) {
		System.out.println(description);
		validateCommonResponseStructure(response);
	}

	private void validateNotFoundResponse(JsonPath response, String description) {
		System.out.println(description);
		validateCommonResponseStructure(response);
	}

	private void validateUnprocessableEntityResponse(JsonPath response, String description) {
		System.out.println(description);
		validateCommonResponseStructure(response);
	}

	private void validateCommonResponseStructure(JsonPath response) {
		MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));
		MatcherAssert.assertThat(response.getString("code").length(), lessThanOrEqualTo(3));

		MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));
		MatcherAssert.assertThat(response.getString("message").length(), lessThanOrEqualTo(250));

		MatcherAssert.assertThat(response.get("type"), instanceOf(String.class));
		MatcherAssert.assertThat(response.getString("type"), anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
		MatcherAssert.assertThat(response.getString("type").length(), lessThanOrEqualTo(1));
	}

}
