// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /cancelProductOrder/{order.Id}_post for http method type POST in rest-assured framework

RoostTestHash=d7d8ad1c4d


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;
import org.json.JSONObject;
import org.json.XML;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class cancelProductOrderOrderIdPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "order.Id", "nnnn_BASE_URL" };
		envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/cancelProductOrder_order.IdPostTest.csv",
				envVarsList);
	}

	@Test
	public void cancelProductOrderOrderIdPost_Test() {
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "");

			JSONObject requestBodyObject = testData.containsKey("RequestBody")
					? new JSONObject(testData.get("RequestBody")) : new JSONObject();
			Response response = given().pathParam("order.Id", testData.getOrDefault("order.Id", ""))
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.post("/cancelProductOrder/{order.Id}")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case %d: cancelProductOrderOrderIdPost_Test \n", testNumber++);
			System.out.println("Request: POST /cancelProductOrder/{order.Id}");
			System.out.println("Status Code: " + response.statusCode());

			validateResponse(response, testData.get("statusCode"));
		}
	}

	private void validateResponse(Response response, String expectedStatusCode) {
		String contentType = response.contentType();
		MatcherAssert.assertThat(contentType, containsString("application/json"));

		if (expectedStatusCode != null) {
			if (expectedStatusCode.contains("X")) {
				MatcherAssert.assertThat("Expected status code category " + expectedStatusCode.charAt(0),
						String.valueOf(response.statusCode()).charAt(0), equalTo(expectedStatusCode.charAt(0)));
			}
			else {
				MatcherAssert.assertThat(response.statusCode(), equalTo(Integer.parseInt(expectedStatusCode)));
			}
		}
		else {
			List<Integer> expectedStatusCodes = Arrays.asList(200, 400, 401, 403, 404, 406, 423, 429, 500, 503, 504);
			MatcherAssert.assertThat(response.statusCode(), is(in(expectedStatusCodes)));
		}

		JsonPath responseJson = response.jsonPath();
		switch (response.statusCode()) {
			case 400:
				validateBadRequestResponse(responseJson);
				break;
			case 404:
				validateNotFoundResponse(responseJson);
				break;
			case 422:
				validateUnprocessableEntityResponse(responseJson);
				break;
		}
	}

	private void validateBadRequestResponse(JsonPath responseJson) {
		MatcherAssert.assertThat(responseJson.getString("error"), notNullValue());
		MatcherAssert.assertThat(responseJson.getString("error_description"), notNullValue());
	}

	private void validateNotFoundResponse(JsonPath responseJson) {
		MatcherAssert.assertThat(responseJson.getString("error"), equalTo("Not Found"));
		MatcherAssert.assertThat(responseJson.getString("message"), containsString("not found"));
	}

	private void validateUnprocessableEntityResponse(JsonPath responseJson) {
		MatcherAssert.assertThat(responseJson.getString("error"), equalTo("Unprocessable Entity"));
		MatcherAssert.assertThat(responseJson.getList("errors"), not(empty()));
	}

}
