// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/productOrderInformationRequiredEvent_post for http method type POST in rest-assured framework

RoostTestHash=38940cf9e7


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.*;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

public class ListenerProductOrderInformationRequiredEventPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	private void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "nnnn_BASE_URL" };
		envList = dataloader.load(
				"src\\test\\java\\com\\bootexample4\\RoostTest\\listener_productOrderInformationRequiredEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void testListenerProductOrderInformationRequiredEventPost() throws JSONException {
		setUp();

		int testNumber = 1;
		for (Map<String, String> testData : envList) {
			String baseUrl = Optional.ofNullable(testData.get("nnnn_BASE_URL")).orElse("");

			RestAssured.baseURI = baseUrl;

			JSONObject requestBody = Optional.ofNullable(testData.get("RequestBody"))
				.map(JSONObject::new)
				.orElse(new JSONObject());

			Response responseObj = given().contentType(ContentType.JSON)
				.body(requestBody.toString())
				.when()
				.post("/listener/productOrderInformationRequiredEvent")
				.then()
				.extract()
				.response();

			JsonPath response;
			String contentType = responseObj.getContentType();
			int responseStatusCode = responseObj.statusCode();

			// Output Test details
			System.out.printf("Test Case %d: listenerProductOrderInformationRequiredEventPost_Test \n", testNumber++);
			System.out.println("Request: POST /listener/productOrderInformationRequiredEvent");
			System.out.println("Status Code: " + responseStatusCode);

			validateResponseStatusCode(responseStatusCode, testData);

			String stringifiedResponseStatusCode = Integer.toString(responseStatusCode);

			if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
				JSONObject jsonData = XML.toJSONObject(responseObj.asString()).getJSONObject("xml");
				response = new JsonPath(jsonData.toString());
			}
			else if (contentType.contains("application/json")) {
				response = responseObj.jsonPath();
			}
			else {
				System.out.println("Response content type found: " + contentType
						+ ", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
				continue;
			}

			printDescriptionForResultedStatusCode(stringifiedResponseStatusCode);
		}
	}

	private void validateResponseStatusCode(int responseStatusCode, Map<String, String> testData) {
		String expectedStatusCode = testData.get("statusCode");

		if (nonNull(expectedStatusCode)) {
			if (expectedStatusCode.endsWith("X")) {
				MatcherAssert.assertThat(
						"Expected a status code of category " + expectedStatusCode + ", but got " + responseStatusCode
								+ " instead",
						responseStatusCode / 100,
						equalTo(Integer.parseInt(String.valueOf(expectedStatusCode.charAt(0)))));
			}
			else {
				MatcherAssert.assertThat(responseStatusCode, equalTo(Integer.parseInt(expectedStatusCode)));
			}
		}
		else {
			MatcherAssert.assertThat(responseStatusCode, is(in(Arrays.asList(204, 400, 401, 500, 503, 504))));
		}
	}

	private void printDescriptionForResultedStatusCode(String stringifiedResponseStatusCode) {
		Map<String, String> statusCodeDescriptionMap = new HashMap<String, String>() {
			{
				put("204", "Success");
				put("400", "BadRequest");
				put("401", "Unauthorized");
				put("500", "ServerError");
				put("503", "Unavailable");
				put("504", "Timeout");
			}
		};

		Optional.ofNullable(statusCodeDescriptionMap.get(stringifiedResponseStatusCode)).ifPresent(System.out::println);
	}

}
