// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /listener/productOrderStateChangeEvent_post for http method type POST in rest-assured framework

RoostTestHash=54c0d3bea0


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

public class ListenerProductOrderStateChangeEventPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "nnnn_BASE_URL" };
		envList = dataLoader.load(
				"src/test/java/com/bootexample4/RoostTest/listener_productOrderStateChangeEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerProductOrderStateChangeEventPost_Test() throws JSONException {
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "");

			JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));

			Response response = given().contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.post("/listener/productOrderStateChangeEvent")
				.then()
				.extract()
				.response();

			JsonPath responseJsonPath = parseResponse(response);
			validateResponse(testData, response, testNumber++);
		}
	}

	private JsonPath parseResponse(Response response) {
		String contentType = response.getContentType();
		if (contentType.contains("application/json")) {
			return response.jsonPath();
		}
		else if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			JSONObject xmlToJson = XML.toJSONObject(response.asString());
			return new JsonPath(xmlToJson.toString());
		}
		else {
			throw new IllegalArgumentException("Unsupported content type: " + contentType);
		}
	}

	private void validateResponse(Map<String, String> testData, Response response, int testNumber) {
		System.out.printf("Test Case %d: listenerProductOrderStateChangeEventPost_Test \n", testNumber);
		System.out.println("Request: POST /listener/productOrderStateChangeEvent");
		System.out.println("Status Code: " + response.statusCode());

		String expectedStatusCode = testData.get("statusCode");
		if (expectedStatusCode != null) {
			if (expectedStatusCode.contains("X")) {
				assertThat("Expected status code category differs", String.valueOf(response.statusCode()).charAt(0),
						equalTo(expectedStatusCode.charAt(0)));
			}
			else {
				assertThat("Expected status code mismatch", response.statusCode(),
						equalTo(Integer.parseInt(expectedStatusCode)));
			}
		}
		else {
			List<Integer> expectedStatusCodes = Arrays.asList(204, 400, 401, 500, 503, 504);
			assertThat("Unexpected status code", response.statusCode(), is(in(expectedStatusCodes)));
		}

		switch (response.statusCode()) {
			case 400:
				validateErrorResponse(responseJsonPath);
				break;
			case 404:
				validateNotFoundResponse(responseJsonPath);
				break;
			case 422:
				validateUnprocessableEntityResponse(responseJsonPath);
				break;
			default:
				System.out.println("No special validation for status code: " + response.statusCode());
		}
	}

	private void validateErrorResponse(JsonPath jsonPath) {
		assertThat("Error message is missing", jsonPath.getString("error"), notNullValue());
	}

	private void validateNotFoundResponse(JsonPath jsonPath) {
		assertThat("Not Found message is missing", jsonPath.getString("message"), equalTo("Resource not found"));
	}

	private void validateUnprocessableEntityResponse(JsonPath jsonPath) {
		assertThat("Details of unprocessable entity are missing", jsonPath.getList("errors"), not(empty()));
	}

}
