// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/productOrderCreateEvent_post for http method type POST in rest-assured framework

RoostTestHash=9dc9fae927


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

public class ListenerProductOrderCreateEventPostTest {

	List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "nnnn_BASE_URL" };
		envList = dataloader.load(
				"src\\test\\java\\com\\bootexample4\\RoostTest\\ListenerProductOrderCreateEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerProductOrderCreateEventPost_Test() {
		setUp();
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "");

			Map<String, Object> requestBodyObject = testData.get("RequestBody") == null ? new HashMap<>()
					: new Gson().fromJson(testData.get("RequestBody"), Map.class);

			RestAssured.given()
				.contentType(ContentType.JSON)
				.body(requestBodyObject)
				.when()
				.post("/listener/productOrderCreateEvent")
				.then()
				.assertThat()
				.contentType(ContentType.JSON)
				.statusCode(isOneOf(204, 400, 401, 500, 503, 504))
				.body("stausMessage", equalTo(resolveStatusCodeMessage(response.getStatusCode())))
				.extract()
				.path();

		}
	}

	private String resolveStatusCodeMessage(int statusCode) {
		switch (statusCode) {
			case 204:
				return "Operation performed successfully";
			case 400:
				return "Bad Request";
			case 401:
				return "Unauthorized";
			case 500:
				return "Server Error";
			case 503:
				return "Service Unavailable";
			case 504:
				return "Gateway Timeout";
			default:
				return "Unknown status code";
		}
	}

}
