// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /listener/productOrderCreateEvent_post for http method type POST in rest-assured framework

RoostTestHash=9dc9fae927


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import org.json.JSONObject;
import org.json.XML;

public class ListenerProductOrderCreateEventPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "nnnn_BASE_URL" };
		envList = dataLoader
			.load("src/test/java/com/bootexample4/RoostTest/listener_productOrderCreateEventPostTest.csv", envVarsList);
	}

	@Test
	public void listenerProductOrderCreateEventPostTest() {
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "");

			JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));
			Response response = given().contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.post("/listener/productOrderCreateEvent")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case: listenerProductOrderCreateEventPostTest \n");
			System.out.println("Request: POST /listener/productOrderCreateEvent");
			System.out.println("Status Code: " + response.statusCode());

			validateResponseByStatusCode(response);
		}
	}

	private void validateResponseByStatusCode(Response response) {
		int statusCode = response.statusCode();
		switch (statusCode) {
			case 204:
				System.out.println("Description: Operation succeeded");
				break;
			case 400:
				validateErrorResponse(response);
				break;
			case 404:
				validateNotFoundResponse(response);
				break;
			case 422:
				validateUnprocessableEntityResponse(response);
				break;
			default:
				System.out.println("Unexpected status code received: " + statusCode);
		}
	}

	private void validateErrorResponse(Response response) {
		JsonPath jsonPath = response.jsonPath();
		MatcherAssert.assertThat("Error message should be present", jsonPath.getString("error"), notNullValue());
		MatcherAssert.assertThat("Error code should be 400", jsonPath.getInt("status"), equalTo(400));
	}

	private void validateNotFoundResponse(Response response) {
		JsonPath jsonPath = response.jsonPath();
		MatcherAssert.assertThat("Not found message should be present", jsonPath.getString("message"),
				equalTo("Resource not found"));
		MatcherAssert.assertThat("Error code should be 404", jsonPath.getInt("status"), equalTo(404));
	}

	private void validateUnprocessableEntityResponse(Response response) {
		JsonPath jsonPath = response.jsonPath();
		MatcherAssert.assertThat("Validation errors should be present", jsonPath.getList("errors"), not(empty()));
		MatcherAssert.assertThat("Error code should be 422", jsonPath.getInt("status"), equalTo(422));
	}

}
