// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /listener/productOrderInformationRequiredEvent_post for http method type POST in rest-assured framework

RoostTestHash=38940cf9e7


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.http.ContentType;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.json.XML;
import java.util.List;
import java.util.Map;

public class ListenerProductOrderInformationRequiredEventPostTest {

	private List<Map<String, String>> envList;

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "nnnn_BASE_URL" };
		envList = dataLoader.load(
				"src/test/java/com/bootexample4/RoostTest/listener_productOrderInformationRequiredEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerProductOrderInformationRequiredEventPostTest() {
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			String baseUrl = testData.getOrDefault("nnnn_BASE_URL", "");
			RestAssured.baseURI = baseUrl;

			JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));
			Response response = given().contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.post("/listener/productOrderInformationRequiredEvent")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case %d: listenerProductOrderInformationRequiredEventPostTest \n", testNumber++);
			System.out.println("Request: POST /listener/productOrderInformationRequiredEvent");
			System.out.println("Status Code: " + response.statusCode());
			validateResponse(testData, response);

			JsonPath responseJson = parseResponse(response);
			validateErrorResponse(responseJson, response.statusCode());
		}
	}

	private void validateResponse(Map<String, String> testData, Response response) {
		if (testData.containsKey("statusCode")) {
			String statusCodeFromCSV = testData.get("statusCode");
			if (statusCodeFromCSV.contains("X")) {
				assertThat("Expected a status code category mismatch",
						Integer.toString(response.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
			}
			else {
				assertThat("Status code mismatch", Integer.toString(response.statusCode()), equalTo(statusCodeFromCSV));
			}
		}
		else {
			List<Integer> expectedStatusCodes = List.of(204, 400, 401, 500, 503, 504);
			assertThat("Unexpected status code", response.statusCode(), is(in(expectedStatusCodes)));
		}
	}

	private JsonPath parseResponse(Response response) {
		String contentType = response.getContentType();
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			JSONObject jsonResponse = XML.toJSONObject(response.asString());
			return new JsonPath(jsonResponse.toString());
		}
		else if (contentType.contains("application/json")) {
			return response.jsonPath();
		}
		else {
			System.out.println("Unsupported content type: " + contentType);
			return null;
		}
	}

	private void validateErrorResponse(JsonPath jsonPath, int statusCode) {
		switch (statusCode) {
			case 400:
				assertThat(jsonPath.getString("error"), equalTo("Bad Request"));
				assertThat(jsonPath.getString("message"), not(isEmptyOrNullString()));
				break;
			case 404:
				assertThat(jsonPath.getString("error"), equalTo("Not Found"));
				assertThat(jsonPath.getString("message"), not(isEmptyOrNullString()));
				break;
			case 422:
				assertThat(jsonPath.getString("error"), equalTo("Unprocessable Entity"));
				assertThat(jsonPath.getString("details"), not(isEmptyOrNullString()));
				break;
		}
	}

}
