// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/productOrderStateChangeEvent_post for http method type POST in rest-assured framework

RoostTestHash=d8e209ebde


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Arrays;

public class ListenerProductOrderStateChangeEventPostTest {

	private static final List<Integer> EXPECTED_STATUS_CODES = Arrays.asList(204, 400, 401, 500, 503, 504);

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataloader.load(
				"src/test/java/com/bootexample4/RoostTest/listener_productOrderStateChangeEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerProductOrderStateChangeEventPost_Test() throws JSONException {
		int testNumber = 1;

		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://127.0.0.1:4021");

			JSONObject requestBody = getRequestBody(testData.get("RequestBody"));

			Response responseObj = given().contentType(ContentType.JSON)
				.body(requestBody.toString())
				.when()
				.post("/listener/productOrderStateChangeEvent")
				.then()
				.extract()
				.response();

			validateResponse(testNumber++, testData, responseObj);
		}
	}

	private JSONObject getRequestBody(String requestBodyString) throws JSONException {
		if (requestBodyString != null) {
			return new JSONObject(requestBodyString);
		}
		return new JSONObject();
	}

	private void validateResponse(int testNumber, Map<String, String> testData, Response responseObj)
			throws JSONException {
		System.out.printf("Test Case %d: listenerProductOrderStateChangeEventPost_Test%n", testNumber);
		System.out.println("Request: POST /listener/productOrderStateChangeEvent");
		System.out.println("Status Code: " + responseObj.statusCode());

		validateStatusCode(testData, responseObj);

		JsonPath response = parseResponse(responseObj);
		if (response != null) {
			String statusCode = Integer.toString(responseObj.statusCode());

			switch (statusCode) {
				case "204" -> System.out.println("Description: Operation successful");
				case "400" -> validateErrorResponse(response);
				case "404" -> validateNotFoundResponse(response);
				case "422" -> validateUnprocessableEntityResponse(response);
				default -> System.out.println("Unhandled response status code: " + statusCode);
			}
		}
	}

	private void validateStatusCode(Map<String, String> testData, Response responseObj) {
		int actualStatusCode = responseObj.statusCode();

		if (testData.containsKey("statusCode")) {
			String expectedStatusCode = testData.get("statusCode");

			if (expectedStatusCode.contains("X")) {
				assertThat("Expected a status code of category " + expectedStatusCode,
						String.valueOf(actualStatusCode).charAt(0), equalTo(expectedStatusCode.charAt(0)));
			}
			else {
				assertThat(String.valueOf(actualStatusCode), equalTo(expectedStatusCode));
			}
		}
		else {
			assertThat(actualStatusCode, is(in(EXPECTED_STATUS_CODES)));
		}
	}

	private JsonPath parseResponse(Response responseObj) throws JSONException {
		String contentType = responseObj.getContentType();

		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = responseObj.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
			return new JsonPath(jsonResponse.toString());
		}
		else if (contentType.contains("application/json")) {
			return responseObj.jsonPath();
		}
		else {
			System.out.println("Unsupported response content type: " + contentType);
			return null;
		}
	}

	private void validateErrorResponse(JsonPath response) {
		assertThat("Error details should exist", response.getString("error.details"), notNullValue());
		assertThat("Invalid request error message", response.getString("error.message"), containsString("Bad Request"));
		assertThat("HTTP status code validation", response.getInt("error.status"), is(400));
	}

	private void validateNotFoundResponse(JsonPath response) {
		assertThat("Error details should exist", response.getString("error.details"), notNullValue());
		assertThat("Not Found error message", response.getString("error.message"), containsString("Not Found"));
		assertThat("HTTP status code validation", response.getInt("error.status"), is(404));
	}

	private void validateUnprocessableEntityResponse(JsonPath response) {
		assertThat("Error details should exist", response.getString("error.details"), notNullValue());
		assertThat("Unprocessable Entity error message", response.getString("error.message"),
				containsString("Unprocessable Entity"));
		assertThat("HTTP status code validation", response.getInt("error.status"), is(422));
	}

}
