// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/cancelProductOrderCreateEvent_post for http method type POST in rest-assured framework

RoostTestHash=e38835f07d


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.in;
import org.json.*;

public class ListenerCancelProductOrderCreateEventPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = {};
		envList = dataloader.load(
				"src/test/java/com/bootexample4/RoostTest/listener_cancelProductOrderCreateEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerCancelProductOrderCreateEventPost_Test() throws JSONException {
		this.setUp();
		int testNumber = 1;
		for (Map<String, String> testData : envList) {
			String baseUrl = testData.get("nnnn_BASE_URL");
			RestAssured.baseURI = (baseUrl != null && !baseUrl.isEmpty()) ? baseUrl : "http://127.0.0.1:4015";

			JSONObject requestBodyObject = new JSONObject(Optional.ofNullable(testData.get("RequestBody")).orElse(""));

			Response responseObj = given().contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.post("/listener/cancelProductOrderCreateEvent")
				.then()
				.extract()
				.response();

			JsonPath response;
			String contentType = responseObj.getContentType();

			System.out.printf("Test Case %d: listenerCancelProductOrderCreateEventPost_Test \n", testNumber++);
			System.out.println("Request: POST /listener/cancelProductOrderCreateEvent");
			System.out.println("Status Code: " + responseObj.statusCode());

			extractResponseData(testData, responseObj);

			response = parseResponse(contentType, responseObj);
			validateResponseByStatusCode(responseObj);
		}
	}

	private void extractResponseData(Map<String, String> testData, Response responseObj) {
		String statusCodeFromCSV = testData.get("statusCode");
		if (statusCodeFromCSV != null) {
			if (statusCodeFromCSV.contains("X")) {
				assertThat(
						"Expected a status code of category " + statusCodeFromCSV + ", but got "
								+ responseObj.statusCode() + " instead",
						Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
			}
			else {
				assertThat(Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
			}
		}
		else {
			assertStatusCodeInList(responseObj);
		}
	}

	private void assertStatusCodeInList(Response responseObj) {
		List<Integer> expectedStatusCodes = Arrays.asList(204, 400, 401, 500, 503, 504);
		assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
	}

	private JsonPath parseResponse(String contentType, Response responseObj) {
		JsonPath response;
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = responseObj.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
			JSONObject jsonData = jsonResponse.getJSONObject("xml");
			String jsonString = jsonData.toString();
			response = new JsonPath(jsonString);
		}
		else if (contentType.contains("application/json")) {
			response = responseObj.jsonPath();
		}
		else {
			System.out.println("Invalid Response content type found: " + contentType
					+ ". Only the following response content types are supported: application/json,text/xml,application/xml");
			// break loop if invalid content type is found
			throw new RuntimeException();
		}
		return response;
	}

	// You would need to replace placeholders with your actual error response fields
	private void validateResponseByStatusCode(Response responseObj) {
		String stringStatusCode = Integer.toString(responseObj.statusCode());
		switch (stringStatusCode) {
			case "204":
				System.out.println("Description: Operation completed successfully");
				// validation logic when response status is 204
				break;
			case "400":
				System.out.println("Description: BadRequest");
				// validation logic when response status is 400
				validateErrorResponse(responseObj);
				break;
			case "401":
				System.out.println("Description: Unauthorized");
				// validation logic when response status is 401
				break;
			case "500":
				System.out.println("Description: ServerError");
				// validation logic when response status is 500
				break;
			case "503":
				System.out.println("Description: Unavailable");
				// validation logic when response status is 503
				break;
			case "504":
				System.out.println("Description: Timeout");
				// validation logic when response status is 504
				break;
			default:
				break;
		}
	}

	private void validateErrorResponse(Response responseObj) {
		// Validation logic when response has status code 400,
		// e.g. responseObj.then().body("error.message", equalTo("Expected error
		// message"));
	}

	private void validateNotFoundResponse(Response responseObj) {
		// Validation logic when response has status code 404,
	}

	private void validateUnprocessableEntityResponse(Response responseObj) {
		// Validation logic when response has status code 422,
	}

}
