// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/cancelProductOrderCreateEvent_post for http method type POST in rest-assured framework

RoostTestHash=e38835f07d


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import java.util.Arrays;

public class ListenerCancelProductOrderCreateEventPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataloader.load(
				"src\\test\\java\\com\\bootexample4\\RoostTest\\listener_cancelProductOrderCreateEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerCancelProductOrderCreateEventPost_Test() throws JSONException {
		setUp();
		int testCounter = 1;

		for (Map<String, String> testData : envList) {
			String baseUrl = testData.getOrDefault("nnnn_BASE_URL", "http://127.0.0.1:4026");
			RestAssured.baseURI = baseUrl;

			JSONObject requestBody = new JSONObject();
			if (testData.get("RequestBody") != null) {
				requestBody = new JSONObject(testData.get("RequestBody"));
			}

			Response response = given().contentType(ContentType.JSON)
				.body(requestBody.toString())
				.post("/listener/cancelProductOrderCreateEvent")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case %d: listenerCancelProductOrderCreateEventPost_Test%n", testCounter++);
			System.out.println("Request: POST /listener/cancelProductOrderCreateEvent");
			System.out.println("Status Code: " + response.statusCode());

			validateStatusCode(response, testData);
			processResponse(response);
		}
	}

	private void validateStatusCode(Response response, Map<String, String> testData) {
		String expectedStatusCode = testData.get("statusCode");

		if (expectedStatusCode != null) {
			if (expectedStatusCode.contains("X")) { // Checking status code category
				char expectedCategory = expectedStatusCode.charAt(0);
				assertThat(
						"Expected a status code of category " + expectedCategory + ", but got " + response.statusCode(),
						String.valueOf(response.statusCode()).charAt(0), equalTo(expectedCategory));
			}
			else { // Direct status code match
				assertThat("Expected status code does not match.", response.statusCode(),
						equalTo(Integer.parseInt(expectedStatusCode)));
			}
		}
		else {
			List<Integer> allowedStatusCodes = Arrays.asList(204, 400, 401, 500, 503, 504);
			assertThat(response.statusCode(), is(in(allowedStatusCodes)));
		}
	}

	private void processResponse(Response response) throws JSONException {
		String contentType = response.getContentType();
		JsonPath jsonResponse;

		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = response.asString();
			JSONObject convertedToJson = XML.toJSONObject(xmlResponse);
			String jsonString = convertedToJson.getJSONObject("xml").toString();
			jsonResponse = new JsonPath(jsonString);

		}
		else if (contentType.contains("application/json")) {
			jsonResponse = response.jsonPath();

		}
		else {
			System.out.println("Unsupported response content type: " + contentType);
			return;
		}

		switch (response.statusCode()) {
			case 204:
				System.out.println("Description: Operation successful.");
				break;
			case 400:
				validateErrorResponse(jsonResponse);
				break;
			case 404:
				validateNotFoundResponse(jsonResponse);
				break;
			case 422:
				validateUnprocessableEntityResponse(jsonResponse);
				break;
			default:
				System.out.println("Unhandled status code: " + response.statusCode());
		}
	}

	private void validateErrorResponse(JsonPath jsonResponse) {
		assertThat("Error validation failed for status code 400.", jsonResponse.getString("error"), notNullValue());
		assertThat("Error message should be specific to bad request.", jsonResponse.getString("message"),
				containsString("BadRequest"));
	}

	private void validateNotFoundResponse(JsonPath jsonResponse) {
		assertThat("Error validation failed for status code 404.", jsonResponse.getString("error"),
				equalTo("Not Found"));
		assertThat("Error message should indicate the resource was not found.", jsonResponse.getString("message"),
				containsString("Resource not found"));
	}

	private void validateUnprocessableEntityResponse(JsonPath jsonResponse) {
		assertThat("Error validation failed for status code 422.", jsonResponse.getString("error"),
				equalTo("Unprocessable Entity"));
		assertThat("Error message should indicate validation issues.", jsonResponse.getString("message"),
				containsString("Validation failed"));
	}

}
