// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/productOrderCreateEvent_post for http method type POST in rest-assured framework

RoostTestHash=1d1252a960


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.http.ContentType;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class ListenerProductOrderCreateEventPostTest {

	private List<Map<String, String>> testDataList = new ArrayList<>();

	/**
	 * Load environment variables and test data.
	 */
	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "" };
		testDataList = dataLoader
			.load("src/test/java/com/bootexample4/RoostTest/listener_productOrderCreateEventPostTest.csv", envVarsList);
	}

	/**
	 * Main test method for validating the product order creation endpoint.
	 */
	@Test
	public void listenerProductOrderCreateEventPost_Test() throws JSONException {
		this.setUp(); // Ensure environment/setup.
		int testCaseNumber = 1;

		for (Map<String, String> testData : testDataList) {
			// Setting the base URI
			RestAssured.baseURI = getBaseUrl(testData);

			// Prepare the request payload
			JSONObject requestBody = prepareRequestBody(testData);

			// Execute the API call and capture the response
			Response response = executePostRequest(requestBody);

			logTestDetails(testCaseNumber++, response);

			// Validate the response based on status code
			validateResponse(response, testData);
		}
	}

	// ----------------------- Helper Methods -----------------------

	private String getBaseUrl(Map<String, String> testData) {
		return (testData.get("nnnn_BASE_URL") != null && !testData.get("nnnn_BASE_URL").isEmpty())
				? testData.get("nnnn_BASE_URL") : "http://127.0.0.1:4026";
	}

	private JSONObject prepareRequestBody(Map<String, String> testData) {
		try {
			if (testData.get("RequestBody") != null) {
				return new JSONObject(testData.get("RequestBody"));
			}
		}
		catch (JSONException e) {
			System.err.println("Invalid JSON format in RequestBody: " + e.getMessage());
		}
		return new JSONObject(); // Return empty JSON object if RequestBody is null
	}

	private Response executePostRequest(JSONObject requestBody) {
		return given().contentType(ContentType.JSON)
			.body(requestBody.toString())
			.when()
			.post("/listener/productOrderCreateEvent")
			.then()
			.extract()
			.response();
	}

	private void logTestDetails(int testCaseNumber, Response response) {
		System.out.printf("Test Case %d: Listener ProductOrderCreateEvent POST Test\n", testCaseNumber);
		System.out.println("Request: POST /listener/productOrderCreateEvent");
		System.out.println("Status Code: " + response.statusCode());
		System.out.println("Response Content-Type: " + response.getContentType());
	}

	private void validateResponse(Response response, Map<String, String> testData) {
		int actualStatusCode = response.statusCode();
		String expectedStatusCode = testData.get("statusCode");

		// Validate status code using expected value from CSV (if provided)
		if (expectedStatusCode != null && !expectedStatusCode.isEmpty()) {
			assertThat("Unexpected status code!", Integer.toString(actualStatusCode), equalTo(expectedStatusCode));
		}
		else {
			List<Integer> validStatusCodes = Arrays.asList(204, 400, 401, 500, 503, 504);
			assertThat("Unexpected status code!", actualStatusCode, is(in(validStatusCodes)));
		}

		// Delegate error response validations based on actual status code
		switch (actualStatusCode) {
			case 400:
				validateErrorResponse(response);
				break;
			case 404:
				validateNotFoundResponse(response);
				break;
			case 422:
				validateUnprocessableEntityResponse(response);
				break;
			// You can extend this for other status codes if necessary
		}
	}

	// ----------------------- Error Response Validations -----------------------

	private void validateErrorResponse(Response response) {
		System.out.println("Validating 400 Bad Request response...");
		assertThat(response.statusCode(), is(400));
		JsonPath jsonResponse = response.jsonPath();
		assertThat(jsonResponse.getString("error.message"), notNullValue());
		assertThat(jsonResponse.getString("error.details"), containsString("Invalid input"));
	}

	private void validateNotFoundResponse(Response response) {
		System.out.println("Validating 404 Not Found response...");
		assertThat(response.statusCode(), is(404));
		JsonPath jsonResponse = response.jsonPath();
		assertThat(jsonResponse.getString("error.message"), equalTo("Resource not found"));
	}

	private void validateUnprocessableEntityResponse(Response response) {
		System.out.println("Validating 422 Unprocessable Entity response...");
		assertThat(response.statusCode(), is(422));
		JsonPath jsonResponse = response.jsonPath();
		assertThat(jsonResponse.getString("error.message"), equalTo("Unprocessable Entity"));
		assertThat(jsonResponse.getString("error.details"), containsString("Validation failed"));
	}

}
