// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /listener/productOrderInformationRequiredEvent_post for http method type POST in rest-assured framework

RoostTestHash=01d41546d2


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.*;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

public class listenerProductOrderInformationRequiredEventPostTest {

	private static final String DEFAULT_BASE_URL = "http://127.0.0.1:4021";

	private List<Map<String, String>> envList;

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataloader.load(
				"src\\test\\java\\com\\bootexample4\\RoostTest\\listener_productOrderInformationRequiredEventPostTest.csv",
				envVarsList);
	}

	@Test
	public void listenerProductOrderInformationRequiredEventPost_Test() throws JSONException {
		setUp();
		int testNumber = 1;

		for (Map<String, String> testData : envList) {
			configureBaseURI(testData);
			JSONObject requestBody = createRequestBody(testData);

			Response response = sendPostRequest(requestBody);

			System.out.printf("Test Case %d: listenerProductOrderInformationRequiredEventPost_Test \n", testNumber++);
			System.out.println("Request: POST /listener/productOrderInformationRequiredEvent");
			System.out.println("Status Code: " + response.statusCode());

			validateResponseStatusCode(testData, response.statusCode());
			validateResponseContentType(response);

			handleResponse(response, testData.get("statusCode"));
		}
	}

	private void configureBaseURI(Map<String, String> testData) {
		String baseUrl = Optional.ofNullable(testData.get("nnnn_BASE_URL"))
			.filter(url -> !url.isEmpty())
			.orElse(DEFAULT_BASE_URL);
		RestAssured.baseURI = baseUrl;
	}

	private JSONObject createRequestBody(Map<String, String> testData) throws JSONException {
		if (testData.get("RequestBody") != null) {
			return new JSONObject(testData.get("RequestBody"));
		}
		return new JSONObject();
	}

	private Response sendPostRequest(JSONObject requestBody) {
		return given().contentType(ContentType.JSON)
			.body(requestBody.toString())
			.when()
			.post("/listener/productOrderInformationRequiredEvent")
			.then()
			.extract()
			.response();
	}

	private void validateResponseStatusCode(Map<String, String> testData, int actualStatusCode) {
		String expectedStatusCode = testData.get("statusCode");
		if (expectedStatusCode != null) {
			if (expectedStatusCode.contains("X")) {
				assertThat("Expected a status code of category " + expectedStatusCode + ", but got " + actualStatusCode,
						Character.toString((char) actualStatusCode),
						equalTo(Character.toString(expectedStatusCode.charAt(0))));
			}
			else {
				assertThat(String.valueOf(actualStatusCode), equalTo(expectedStatusCode));
			}
		}
		else {
			List<Integer> expectedStatusCodes = Arrays.asList(204, 400, 401, 500, 503, 504);
			assertThat(actualStatusCode, is(in(expectedStatusCodes)));
		}
	}

	private void validateResponseContentType(Response response) {
		String contentType = response.getContentType();
		if (!contentType.contains("application/json") && !contentType.contains("application/xml")
				&& !contentType.contains("text/xml")) {
			System.out.println("Unsupported response content type: " + contentType);
		}
	}

	private void handleResponse(Response response, String expectedStatusCode) {
		JsonPath responseJsonPath = parseResponse(response);

		switch (expectedStatusCode) {
			case "204":
				System.out.println("Description: Success");
				break;
			case "400":
				System.out.println("Description: BadRequest");
				validateErrorResponse(responseJsonPath);
				break;
			case "404":
				System.out.println("Description: NotFound");
				validateNotFoundResponse(responseJsonPath);
				break;
			case "422":
				System.out.println("Description: UnprocessableEntity");
				validateUnprocessableEntityResponse(responseJsonPath);
				break;
			default:
				System.out.println("Description: Other");
		}
	}

	private JsonPath parseResponse(Response response) {
		String contentType = response.getContentType();
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = response.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
			return new JsonPath(jsonResponse.toString());
		}
		else if (contentType.contains("application/json")) {
			return response.jsonPath();
		}
		return null;
	}

	private void validateErrorResponse(JsonPath response) {
		assertThat(response.getString("error"), notNullValue());
		assertThat(response.getString("message"), notNullValue());
		assertThat(response.getInt("status"), equalTo(400));
	}

	private void validateNotFoundResponse(JsonPath response) {
		assertThat(response.getString("error"), equalTo("Not Found"));
		assertThat(response.getString("message"), notNullValue());
		assertThat(response.getInt("status"), equalTo(404));
	}

	private void validateUnprocessableEntityResponse(JsonPath response) {
		assertThat(response.getString("error"), equalTo("Unprocessable Entity"));
		assertThat(response.getString("message"), notNullValue());
		assertThat(response.getInt("status"), equalTo(422));
		assertThat(response.getList("details"), not(empty()));
	}

}
