// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /productOrder/{order.Id}_patch for http method type PATCH in rest-assured framework

RoostTestHash=2d61156ff7


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

public class ProductOrderOrderIdPatchTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	private TestdataLoader dataLoader = new TestdataLoader();

	private String[] envVarsList = { "orderId" };

	private List<Integer> expectedStatusCodes = Arrays.asList(200, 400, 401, 403, 404, 406, 429, 500, 503, 504);

	@BeforeEach
	public void setUp() throws IOException {
		envList = dataLoader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\ProductOrderOrderIdPatchTest.csv",
				envVarsList);
	}

	@Test
	public void productOrderOrderIdPatch_Test() {
		int testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = getBaseUri(testData);

			JSONObject requestBodyObject = getRequestBody(testData);
			Response responseObj = sendRequest(testData, requestBodyObject);

			printTestInformation(testNumber++, responseObj);

			assertStatusCode(testData, responseObj);
			String contentType = assertContentType(responseObj);

			JsonPath response = getResponseJsonPath(contentType, responseObj);

			String code = response.getString("code");
			String message = response.getString("message");
			String type = response.getString("type");

			validateResponse(code, message, type);
		}
	}

	private String getBaseUri(Map<String, String> testData) {
		return testData.getOrDefault("nnnn_BASE_URL", "http://localhost:8080");
	}

	private JSONObject getRequestBody(Map<String, String> testData) {
		String requestBody = testData.getOrDefault("RequestBody", "{}");
		return new JSONObject(requestBody);
	}

	private Response sendRequest(Map<String, String> testData, JSONObject requestBodyObject) {
		String orderId = testData.getOrDefault("orderId", "");
		return given().pathParam("orderId", orderId)
			.contentType(ContentType.JSON)
			.body(requestBodyObject.toString())
			.when()
			.patch("/productOrder/{orderId}")
			.then()
			.extract()
			.response();
	}

	private void printTestInformation(int testNumber, Response responseObj) {
		System.out.printf("Test Case %d: ProductOrderOrderIdPatchTest \n", testNumber);
		System.out.println("Request: PATCH /productOrder/{orderId}");
		System.out.println("Status Code: " + responseObj.statusCode());
	}

	private void assertStatusCode(Map<String, String> testData, Response responseObj) {
		String statusCode = testData.get("statusCode");
		if (statusCode == null) {
			assertThat(responseObj.statusCode(), is(expectedStatusCodes));
		}
		else if (statusCode.contains("X")) {
			assertThat(Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCode.charAt(0)));
		}
		else {
			assertThat(Integer.toString(responseObj.statusCode()), equalTo(statusCode));
		}
	}

	private String assertContentType(Response responseObj) {
		String contentType = responseObj.contentType();
		assertThat(contentType, equalTo("application/json"));
		return contentType;
	}

	private JsonPath getResponseJsonPath(String contentType, Response responseObj) {
		if (!contentType.contains("application/json")) {
			// add logic for handling different contentTypes
			System.out.println("Unexpected response contentType: " + contentType);
		}
		return responseObj.jsonPath();
	}

	private void validateResponse(String code, String message, String type) {
		assertThat(code, instanceOf(String.class));
		assertThat(code.length(), lessThanOrEqualTo(3));
		assertThat(message, instanceOf(String.class));
		assertThat(message.length(), lessThanOrEqualTo(250));
		assertThat(type, instanceOf(String.class));
		assertThat(type, anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
		assertThat(type.length(), lessThanOrEqualTo(1));
	}

}
