// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /productOrder/{order.Id}_patch for http method type PATCH in rest-assured framework

RoostTestHash=2d61156ff7


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import org.hamcrest.MatcherAssert;

public class ProductOrderOrderIdPatchTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "order.Id", "nnnn_BASE_URL" };
		envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/productOrder_order.IdPatchTest.csv",
				envVarsList);
	}

	@Test
	public void productOrderOrderIdPatchTest() {
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "");

			JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));
			Response response = given().pathParam("order.Id", testData.getOrDefault("order.Id", ""))
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.patch("/productOrder/{order.Id}")
				.then()
				.extract()
				.response();

			JsonPath responseJson = response.jsonPath();
			String contentType = response.getContentType();
			int statusCode = response.statusCode();

			System.out.printf("Test Case %d: productOrderOrderIdPatchTest \n", testNumber++);
			System.out.println("Request: PATCH /productOrder/{order.Id}");
			System.out.println("Status Code: " + statusCode);

			validateResponseBasedOnStatusCode(statusCode, contentType, responseJson);
		}
	}

	private void validateResponseBasedOnStatusCode(int statusCode, String contentType, JsonPath responseJson) {
		MatcherAssert.assertThat("Unexpected Content-Type", contentType, containsString("application/json"));

		if (statusCode == 200) {
			validateSuccessResponse(responseJson);
		}
		else if (statusCode == 400) {
			validateBadRequestResponse(responseJson);
		}
		else if (statusCode == 404) {
			validateNotFoundResponse(responseJson);
		}
		else if (statusCode == 422) {
			validateUnprocessableEntityResponse(responseJson);
		}
		else {
			System.out.println("Unhandled status code: " + statusCode);
		}
	}

	private void validateSuccessResponse(JsonPath response) {
		// Example of validating expected fields in a successful response
		MatcherAssert.assertThat("Missing 'success' field", response.get("success"), is(true));
		MatcherAssert.assertThat("Missing 'data' field", response.get("data"), notNullValue());
	}

	private void validateBadRequestResponse(JsonPath response) {
		// Example of validating a 400 Bad Request response structure
		MatcherAssert.assertThat("Error code is incorrect", response.get("error.code"), is("400"));
		MatcherAssert.assertThat("Error message is incorrect", response.get("error.message"), notNullValue());
	}

	private void validateNotFoundResponse(JsonPath response) {
		// Example of validating a 404 Not Found response structure
		MatcherAssert.assertThat("Error code is incorrect", response.get("error.code"), is("404"));
		MatcherAssert.assertThat("Error message is incorrect", response.get("error.message"),
				equalTo("Resource not found"));
	}

	private void validateUnprocessableEntityResponse(JsonPath response) {
		// Example of validating a 422 Unprocessable Entity response structure
		MatcherAssert.assertThat("Error code is incorrect", response.get("error.code"), is("422"));
		MatcherAssert.assertThat("Details of the error are missing", response.get("error.details"), notNullValue());
	}

}
