// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /productOrder_post for http method type POST in rest-assured framework

RoostTestHash=a5884d9688


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

import org.json.JSONObject;
import org.json.XML;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Arrays;

public class ProductOrderPostTest {

	private List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataLoader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\productOrderPostTest.csv",
				envVarsList);
	}

	@Test
	public void productOrderPostTest() {
		setUp();
		int testNumber = 1;

		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://127.0.0.1:4026");

			JSONObject requestBody = new JSONObject(testData.getOrDefault("RequestBody", "{}"));

			Response response = given().contentType(ContentType.JSON)
				.body(requestBody.toString())
				.when()
				.post("/productOrder")
				.then()
				.extract()
				.response();

			System.out.printf("Test Case %d: productOrderPostTest%n", testNumber++);
			System.out.println("Request: POST /productOrder");
			System.out.println("Status Code: " + response.statusCode());

			validateResponseStatusCode(response.statusCode(), testData);
			String contentType = response.getContentType();

			JsonPath jsonPath = parseResponseContent(response, contentType);

			switch (response.statusCode()) {
				case 201:
					System.out.println("Description: Created");
					validateSuccessResponse(jsonPath);
					break;
				case 400:
					System.out.println("Description: Bad Request");
					validateErrorResponse(jsonPath);
					break;
				case 404:
					System.out.println("Description: Not Found");
					validateNotFoundResponse(jsonPath);
					break;
				case 422:
					System.out.println("Description: Unprocessable Entity");
					validateUnprocessableEntityResponse(jsonPath);
					break;
				default:
					System.out.println("Unhandled status code: " + response.statusCode());
					break;
			}
		}
	}

	private void validateResponseStatusCode(int statusCode, Map<String, String> testData) {
		String statusCodeFromCSV = testData.get("statusCode");

		if (statusCodeFromCSV != null) {
			if (statusCodeFromCSV.contains("X")) {
				assertThat("Expected a status code of category " + statusCodeFromCSV + ", but got " + statusCode,
						Integer.toString(statusCode).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
			}
			else {
				assertThat("Incorrect status code", Integer.toString(statusCode), equalTo(statusCodeFromCSV));
			}
		}
		else {
			List<Integer> expectedStatusCodes = Arrays.asList(201, 400, 401, 403, 404, 406, 429, 500, 503, 504);
			assertThat("Unexpected status code", statusCode, is(in(expectedStatusCodes)));
		}
	}

	private JsonPath parseResponseContent(Response response, String contentType) {
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = response.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
			return new JsonPath(jsonResponse.toString());
		}
		else if (contentType.contains("application/json")) {
			return response.jsonPath();
		}
		else {
			System.out.println("Unsupported Response Content-Type: " + contentType);
			return null;
		}
	}

	private void validateSuccessResponse(JsonPath jsonPath) {
		if (jsonPath.get("control") != null) {
			assertThat(jsonPath.getString("control.code"), instanceOf(String.class));
			assertThat(jsonPath.getString("control.code").length(), lessThanOrEqualTo(3));

			assertThat(jsonPath.getString("control.message"), instanceOf(String.class));
			assertThat(jsonPath.getString("control.message").length(), lessThanOrEqualTo(250));

			assertThat(jsonPath.getString("control.type"), anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
			assertThat(jsonPath.getString("control.type").length(), lessThanOrEqualTo(1));
		}

		if (jsonPath.get("order") != null) {
			assertThat(jsonPath.getString("order.id"), instanceOf(String.class));
			assertThat(jsonPath.getString("order.id").length(), lessThanOrEqualTo(25));
		}
	}

	private void validateErrorResponse(JsonPath jsonPath) {
		assertThat(jsonPath.getString("code"), instanceOf(String.class));
		assertThat(jsonPath.getString("code").length(), lessThanOrEqualTo(3));

		assertThat(jsonPath.getString("message"), instanceOf(String.class));
		assertThat(jsonPath.getString("message").length(), lessThanOrEqualTo(250));

		assertThat(jsonPath.getString("type"), anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
		assertThat(jsonPath.getString("type").length(), lessThanOrEqualTo(1));
	}

	private void validateNotFoundResponse(JsonPath jsonPath) {
		assertThat(jsonPath.getString("code"), instanceOf(String.class));
		assertThat(jsonPath.getString("code").length(), lessThanOrEqualTo(3));

		assertThat(jsonPath.getString("message"), instanceOf(String.class));
		assertThat(jsonPath.getString("message").length(), lessThanOrEqualTo(250));
	}

	private void validateUnprocessableEntityResponse(JsonPath jsonPath) {
		assertThat(jsonPath.getString("code"), instanceOf(String.class));
		assertThat(jsonPath.getString("code").length(), lessThanOrEqualTo(3));

		assertThat(jsonPath.getString("message"), instanceOf(String.class));
		assertThat(jsonPath.getString("message").length(), lessThanOrEqualTo(250));

		assertThat(jsonPath.getString("details"), instanceOf(String.class));
	}

}
