// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /productOrder_post for http method type POST in rest-assured framework

RoostTestHash=a5884d9688


*/

// ********RoostGPT********
package com.bootexample4.roosttest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import java.util.*;

public class ProductOrderPostTest {

	private List<Map<String, String>> testDataList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		String[] envVarsList = { "" };
		testDataList = dataLoader.load("src/test/java/com/bootexample4/roosttest/ProductOrderPostTest.csv",
				envVarsList);
	}

	@Test
	public void productOrderPost_Test() throws JSONException {
		int testCaseNumber = 1;

		for (Map<String, String> testData : testDataList) {
			RestAssured.baseURI = Optional.ofNullable(testData.get("NNNN_BASE_URL"))
				.filter(url -> !url.isEmpty())
				.orElse("http://127.0.0.1:4021");

			JSONObject requestBody = new JSONObject(Optional.ofNullable(testData.get("RequestBody")).orElse("{}"));

			Response response = given().contentType(ContentType.JSON)
				.body(requestBody.toString())
				.when()
				.post("/productOrder")
				.then()
				.extract()
				.response();

			int actualStatusCode = response.statusCode();
			String expectedStatusCode = testData.get("statusCode");

			System.out.printf("Test Case %d: productOrderPost_Test \n", testCaseNumber++);
			System.out.println("Request: POST /productOrder");
			System.out.println("Status Code: " + actualStatusCode);

			// Validate status codes
			validateStatusCode(actualStatusCode, expectedStatusCode);

			// Validate response content
			validateResponseContent(response, actualStatusCode);
		}
	}

	// Method to validate expected and actual status codes
	private void validateStatusCode(int actualStatusCode, String expectedStatusCode) {
		if (expectedStatusCode != null) {
			if (expectedStatusCode.contains("X")) {
				assertThat("Expected a status code of category " + expectedStatusCode + ", but got " + actualStatusCode,
						Integer.toString(actualStatusCode).charAt(0), equalTo(expectedStatusCode.charAt(0)));
			}
			else {
				assertThat("Status code mismatch", Integer.toString(actualStatusCode), equalTo(expectedStatusCode));
			}
		}
		else {
			List<Integer> allowedStatusCodes = Arrays.asList(201, 400, 401, 403, 404, 406, 429, 500, 503, 504);
			assertThat("Unexpected status code", actualStatusCode, is(in(allowedStatusCodes)));
		}
	}

	// Method to validate response content based on status code
	private void validateResponseContent(Response response, int statusCode) {
		String contentType = response.getContentType();
		JsonPath jsonResponse = parseResponseAsJson(response, contentType);

		switch (statusCode) {
			case 201:
				System.out.println("Description: Created");
				validate201Response(jsonResponse);
				break;
			case 400:
				System.out.println("Description: Bad Request");
				validateErrorResponse(jsonResponse);
				break;
			case 404:
				System.out.println("Description: Not Found");
				validateNotFoundResponse(jsonResponse);
				break;
			case 422:
				System.out.println("Description: Unprocessable Entity");
				validateUnprocessableEntityResponse(jsonResponse);
				break;
			default:
				System.out.println("Description: Status code validation skipped for " + statusCode);
		}
	}

	// Parse the response as JSON (handling both JSON and XML)
	private JsonPath parseResponseAsJson(Response response, String contentType) {
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
			String xmlResponse = response.asString();
			JSONObject jsonResponse = XML.toJSONObject(xmlResponse).getJSONObject("xml");
			return new JsonPath(jsonResponse.toString());
		}
		else if (contentType.contains("application/json")) {
			return response.jsonPath();
		}
		else {
			throw new UnsupportedOperationException("Unsupported response type: " + contentType);
		}
	}

	private void validate201Response(JsonPath response) {
		assertThat(response.getString("control.code"), instanceOf(String.class));
		assertThat(response.getString("control.code").length(), lessThanOrEqualTo(3));

		assertThat(response.getString("control.message"), instanceOf(String.class));
		assertThat(response.getString("control.message").length(), lessThanOrEqualTo(250));

		assertThat(response.getString("control.type"), anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
		assertThat(response.getString("control.type").length(), lessThanOrEqualTo(1));

		assertThat(response.getString("order.id"), instanceOf(String.class));
		assertThat(response.getString("order.id").length(), lessThanOrEqualTo(25));
	}

	private void validateErrorResponse(JsonPath response) {
		assertThat(response.getString("code"), instanceOf(String.class));
		assertThat(response.getString("code").length(), lessThanOrEqualTo(3));

		assertThat(response.getString("message"), instanceOf(String.class));
		assertThat(response.getString("message").length(), lessThanOrEqualTo(250));

		assertThat(response.getString("type"), anyOf(equalTo("S"), equalTo("T"), equalTo("E")));
		assertThat(response.getString("type").length(), lessThanOrEqualTo(1));
	}

	private void validateNotFoundResponse(JsonPath response) {
		assertThat(response.getString("code"), equalTo("404"));
		assertThat(response.getString("message"), containsString("Resource not found"));
	}

	private void validateUnprocessableEntityResponse(JsonPath response) {
		assertThat(response.getString("code"), equalTo("422"));
		assertThat(response.getString("message"), containsString("Validation error"));
		assertThat(response.getString("details"), instanceOf(String.class)); // Example
																				// for
																				// additional
																				// field
	}

}
