// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /productOrder/{order.Id}_patch for http method type PATCH in rest-assured framework

RoostTestHash=1ae1afc10a


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class ProductOrderOrderIdPatchTest {

	private static final List<Integer> EXPECTED_STATUS_CODES = Arrays.asList(200, 400, 401, 403, 404, 406, 429, 500,
			503, 504);

	private List<Map<String, String>> envList;

	@BeforeEach
	public void setUp() {
		TestdataLoader dataLoader = new TestdataLoader();
		envList = dataLoader.load("src/test/java/com/bootexample4/RoostTest/productOrder_order.IdPatchTest.csv",
				new String[] { "order.Id" });
	}

	@Test
	public void productOrderOrderIdPatch_Test() throws JSONException {
		int testNumber = 1;

		for (Map<String, String> testData : envList) {
			// Setup
			RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://127.0.0.1:4021");

			JSONObject requestBodyObject = testData.get("RequestBody") != null
					? new JSONObject(testData.get("RequestBody")) : new JSONObject();

			// API Request
			Response response = given().pathParam("order.Id", testData.getOrDefault("order.Id", ""))
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
				.when()
				.patch("/productOrder/{order.Id}")
				.then()
				.extract()
				.response();

			// Logging
			System.out.printf("Test Case %d: productOrderOrderIdPatch_Test%n", testNumber++);
			System.out.println("Request: PATCH /productOrder/{order.Id}");
			System.out.println("Status Code: " + response.statusCode());

			validateHttpStatus(response, testData);

			// Response Validation
			String contentType = response.getContentType();
			JsonPath jsonPathResponse = processResponseContentType(response, contentType);

			handleSuccessOrErrorResponse(response.statusCode(), jsonPathResponse);
		}
	}

	private void validateHttpStatus(Response response, Map<String, String> testData) {
		int actualStatusCode = response.statusCode();

		if (testData.get("statusCode") != null) {
			String expectedStatus = testData.get("statusCode");

			if (expectedStatus.contains("X")) {
				assertThat("Expected a status code of category " + expectedStatus + ", but got " + actualStatusCode,
						Integer.toString(actualStatusCode).charAt(0), equalTo(expectedStatus.charAt(0)));
			}
			else {
				assertThat(actualStatusCode, equalTo(Integer.parseInt(expectedStatus)));
			}
		}
		else {
			assertThat(actualStatusCode, is(in(EXPECTED_STATUS_CODES)));
		}
	}

	private JsonPath processResponseContentType(Response response, String contentType) {
        if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            return XML.toJSONObject(response.asString()).toString().isEmpty() ? null : new JsonPath(response.asString )



    }

 }

}
