# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=a5ea3b10ac
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Cancel product order with valid order ID and request body
    Given path 'cancelProductOrder', '<order_Id>'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 200
    And match response ==
      """
      <expectedResponse>
      """
    And match response.control.code == '200'
    And match response.control.message == 'OK'
    And match response.control.type == 'S'

    Examples:
      | read('cancelProductOrder_order.Id_post.csv') |

  Scenario Outline: Cancel product order with invalid order ID
    Given path 'cancelProductOrder', '<order_Id>'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 404
    And match response ==
      """
      <expectedResponse>
      """
    And match response.control.code == '404'
    And match response.control.message == 'Not Found'
    And match response.control.type == 'E'

    Examples:
      | order_Id        | requestBody                                                                                 | expectedResponse                                                      |
      | 'invalidID1234' | { "order": { "associatedDocument": "VTT001", "customer": { "subscriberId": "SVTAL001" } } } | { "control": { "code": "404", "message": "Not Found", "type": "E" } } |

  Scenario Outline: Cancel product order with unauthorized access
    Given path 'cancelProductOrder', '<order_Id>'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 401
    And match response ==
      """
      <expectedResponse>
      """
    And match response.control.code == '401'
    And match response.control.message == 'Unauthorized'
    And match response.control.type == 'E'

    Examples:
      | order_Id         | requestBody                                                                                 | expectedResponse                                                         |
      | '20230315000001' | { "order": { "associatedDocument": "VTT001", "customer": { "subscriberId": "SVTAL001" } } } | { "control": { "code": "401", "message": "Unauthorized", "type": "E" } } |
