# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=a5ea3b10ac
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Cancel product order with valid order ID and request body
    Given path '<order_Id>'
    And request
      """
      <request_body>
      """
    When method DELETE
    Then status 200
    And match response contains { code: '#string', message: '#string', type: '#string' }
    And match response.path == '/cancelProductOrder'

    Examples:
      | read('cancelProductOrder_order.Id_post.csv') |

  Scenario Outline: Cancel product order with invalid order ID
    Given path '<order_Id>'
    And request
      """
      <request_body>
      """
    When method DELETE
    Then status 404
    And match response contains { code: '#string', message: '#string', type: '#string' }
    And match response.path == '/cancelProductOrder'

    Examples:
      | order_Id         | request_body                                                                                |
      | '20230315000002' | { "order": { "associatedDocument": "VTT002", "customer": { "subscriberId": "SVTAL002" } } } |

  Scenario Outline: Unauthorized request to cancel product order
    Given path '<order_Id>'
    And request
      """
      <request_body>
      """
    When method DELETE
    Then status 401
    And match response contains { code: '#string', message: '#string', type: '#string' }
    And match response.path == '/cancelProductOrder'

    Examples:
      | order_Id         | request_body                                                                                |
      | '20230315000003' | { "order": { "associatedDocument": "VTT003", "customer": { "subscriberId": "SVTAL003" } } } |
