# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=7601d79448
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }
    * url urlBase

  Scenario Outline: Verify successful cancellation of product order creation event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 204
    And match responseHeaders['Content-Type'][0] == 'application/json'
    And match response == {}

    Examples:
      | read('listener_cancelProductOrderCreateEvent_post.csv') |

  Scenario Outline: Verify bad request error when sending invalid data
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 400
    And match response == { "error": "Invalid request data" }

    Examples:
      | requestBody                                                                    |
      | { "notification": { "order": { "associatedDocument": "INVALID", "id": "" } } } |

  Scenario Outline: Verify unauthorized access when no token is provided
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    And header Authorization = ''
    When method POST
    Then status 401
    And match response == { "error": "Unauthorized" }

    Examples:
      | requestBody                                                                                 |
      | { "notification": { "order": { "associatedDocument": "VTT001", "id": "20230315000001" } } } |

  Scenario Outline: Verify server error for internal issues
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 500
    And match response == { "error": "Internal Server Error" }

    Examples:
      | requestBody                                                                                 |
      | { "notification": { "order": { "associatedDocument": "VTT001", "id": "20230315000001" } } } |

  Scenario Outline: Verify service unavailable during downtime
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 503
    And match response == { "error": "Service Unavailable" }

    Examples:
      | requestBody                                                                                 |
      | { "notification": { "order": { "associatedDocument": "VTT001", "id": "20230315000001" } } } |

  Scenario Outline: Verify timeout when the server does not respond in time
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 504
    And match response == { "error": "Timeout" }

    Examples:
      | requestBody                                                                                 |
      | { "notification": { "order": { "associatedDocument": "VTT001", "id": "20230315000001" } } } |
