# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=5d5b9532f3
# 
# 

# ********RoostGPT********
Feature: Testing Product Order Create Event API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Verify successful product order creation with valid data
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      <body>
      """
    When method post
    Then status 204
    And match response == {}

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario Outline: Verify product order creation with invalid data leads to error
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      <body>
      """
    When method post
    Then status 400

    Examples:
      | body                                                                                                                                          |
      | { "notification": { "date": "invalid-date", "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001" } } } |

  Scenario: Unauthorized access to product order creation
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      { "notification": { "date": "2021-06-05T20:23:29-03:00", "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001" } } }
      """
    * configure headers = { Authorization: 'InvalidToken' }
    When method post
    Then status 401

  Scenario: Product order creation server error simulation
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      { "notification": { "date": "2021-06-05T20:23:29-03:00", "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001" } } }
      """
    When method post
    Then status 500

  Scenario: Product order creation timeout simulation
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      { "notification": { "date": "2021-06-05T20:23:29-03:00", "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001" } } }
      """
    When method post
    Then status 504
