# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=ce4c08f30f
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event - API Tests

  Scenario Outline: Validate Product Order Information Request
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = { Authorization: #(karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_AUTH_TOKEN']) }
    Given request
      """
      <requestBody>
      """
    When method POST
    Then status <expectedStatusCode>
    And match response == <expectedResponse>

    Examples:
      | requestBody                                                                                                                                                                                                                                                                                                                                                                 | expectedStatusCode | expectedResponse |
      | """ { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001", "issue": { "action": "abrir", "code": "7029", "description": "Pendencia de agendamento", "fieldActivity": "true", "observation": "", "reason": "PROJETO", "task": "", "type": "CLIENTE", "updateDate": "2021-02-17T17:19:50-03:00" }}}} } """          |                204 | {}               |
      | """ { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001", "issue": { "action": "abrir", "code": "7030", "description": "Pendencia de agendamento", "fieldActivity": "false", "observation": "", "reason": "MANUNTENÇÃO", "task": "", "type": "TECNICA", "updateDate": "2022-02-25T11:50:50.566-03:00" }}}} } """ |                204 | {}               |

  Scenario: Validate Error Response for Bad Request
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = { Authorization: #(karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_AUTH_TOKEN']) }
    Given request
      """
      { "notification": {} }
      """
    When method POST
    Then status 400
    And match response.error == '#string'

  Scenario: Validate Unauthorized Request
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = {}
    Given request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001" } } }
      """
    When method POST
    Then status 401
    And match response.error == '#string'

  Scenario: Validate Server Error Response
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = { Authorization: #(karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_AUTH_TOKEN']) }
    Given request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "INVALID" } } }
      """
    When method POST
    Then status 500
    And match response.error == '#string'

  Scenario: Validate Service Unavailable Response
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = { Authorization: #(karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_AUTH_TOKEN']) }
    Given request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "TIMEOUT_TRIGGER" } } }
      """
    When method POST
    Then status 503
    And match response.error == '#string'

  Scenario: Validate Timeout Response
    * def urlBase = karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_NNNN_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/listener/productOrderInformationRequiredEvent'
    * configure headers = { Authorization: #(karate.properties['nnnn_NNNN_NNNN_NNNN_NNNN_AUTH_TOKEN']) }
    Given request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "TIMEOUT_TEST" } } }
      """
    When method POST
    Then status 504
    And match response.error == '#string'
