# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=ce4c08f30f
# 
# 

# ********RoostGPT********
Feature: Test Product Order Information Required Event API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Verify Product Order Information Required Event API with valid inputs
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      <requestBody>
      """
    When method post
    Then status 204
    And match response == <expectedResponse>

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |

  Scenario: Test POST request with Unauthorized access
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001", "issue": { "action": "abrir", "code": "7029", "description": "Pendencia de agendamento", "fieldActivity": true, "observation": "", "reason": "PROJETO", "task": "", "type": "CLIENTE", "updateDate": "2021-02-17T17:19:50-03:00" } } } }
      """
    And header Authorization = 'InvalidToken'
    When method post
    Then status 401

  Scenario: Test POST request with BadRequest due to missing required fields
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      { "notification": {} }
      """
    When method post
    Then status 400

  Scenario: Test POST request with ServerError simulation
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      { "notification": { "order": { "associatedDocument": "VTT001", "correlationOrder": "10", "id": "20230315000001", "issue": { "action": "abrir", "code": "7029", "description": "Pendencia de agendamento", "fieldActivity": true, "observation": "", "reason": "PROJETO", "task": "", "type": "CLIENTE", "updateDate": "2021-02-17T17:19:50-03:00" } } } }
      """
    And header X-Simulate-Error = 'ServerError'
    When method post
    Then status 500
