# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type  and AI Model 
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=5d5b9532f3
# 
# 

# ********RoostGPT********
Feature: Testing Product Order Create Event API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Verify Product Order Create Event API with valid data
    Given url urlBase
    And path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "id": "<id>",
        "product": "<product>",
        "quantity": "<quantity>",
        "timestamp": "<timestamp>"
      }
      """
    When method post
    Then status 204
    And match response == '#null'

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |
