# ********RoostGPT********

# Test generated by RoostGPT for test sampleArtilleryEnv2 using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=7601d79448
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario: Successfully cancel product order creation event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"VTT001","id":"20230315000001"}}}
      """
    And header Authorization = #(karate.properties['nnnn_AUTH_TOKEN'])
    When method POST
    Then status 204

  Scenario Outline: Test cancel product order creation event with various notification codes
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"<associatedDocument>","id":"<id>"},"code":"<code>"}}
      """
    And header Authorization = #(karate.properties['nnnn_AUTH_TOKEN'])
    When method POST
    Then status <expectedStatus>

    Examples:
      | associatedDocument | id             | code | expectedStatus |
      | VTT001             | 20230315000001 |    0 |            204 |
      | VTT002             | 20230315000002 |    1 |            204 |
      | VTT003             | 20230315000003 |    2 |            204 |
      | VTT004             | 20230315000004 |    3 |            204 |
      | VTT005             | 20230315000005 |    4 |            204 |

  Scenario Outline: Test cancel product order creation event with invalid notification codes
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"<associatedDocument>","id":"<id>"},"code":"<code>"}}
      """
    And header Authorization = #(karate.properties['nnnn_AUTH_TOKEN'])
    When method POST
    Then status <expectedStatus>

    Examples:
      | associatedDocument | id             | code | expectedStatus |
      | VTT001             | 20230315000001 |   -1 |            400 |
      | VTT002             | 20230315000002 |    5 |            400 |

  Scenario: Unauthorized access to cancel product order creation event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"VTT001","id":"20230315000001"}}}
      """
    When method POST
    Then status 401

  Scenario: Server error during cancel product order creation event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"VTT001","id":"20230315000001"}}}
      """
    And header Authorization = #(karate.properties['nnnn_AUTH_TOKEN'])
    When method POST
    Then status 500

  Scenario: Service unavailable during cancel product order creation event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {"notification":{"order":{"associatedDocument":"VTT001","id":"20230315000001"}}}
      """
    And header Authorization = #(karate.properties['nnnn_AUTH_TOKEN'])
    When method POST
    Then status 503
